tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "inverse-primary": "#ffb4a8",
                "tertiary": "#626200",
                "surface": "#f9f9f9",
                "on-primary-fixed-variant": "#930000",
                "surface-variant": "#e2e2e2",
                "surface-dim": "#dadada",
                "outline": "#926e69",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#bfc2ff",
                "on-secondary-fixed-variant": "#1c22d6",
                "on-primary-container": "#ffdad4",
                "secondary-fixed": "#e0e0ff",
                "outline-variant": "#e8bdb6",
                "primary-fixed-dim": "#ffb4a8",
                "on-surface": "#1a1c1c",
                "secondary": "#333ce5",
                "inverse-on-surface": "#f1f1f1",
                "on-background": "#1a1c1c",
                "surface-container": "#eeeeee",
                "on-secondary-container": "#f5f3ff",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#00006e",
                "surface-container-low": "#f3f3f3",
                "error-container": "#ffdad6",
                "surface-tint": "#c00000",
                "error": "#ba1a1a",
                "primary": "#9e0000",
                "on-surface-variant": "#5e3f3a",
                "inverse-surface": "#2f3131",
                "surface-container-highest": "#e2e2e2",
                "background": "#f9f9f9",
                "secondary-container": "#4f59fe",
                "on-tertiary-fixed": "#1d1d00",
                "on-primary-fixed": "#410000",
                "on-tertiary-fixed-variant": "#494900",
                "primary-container": "#cc0000",
                "surface-bright": "#f9f9f9",
                "surface-container-high": "#e8e8e8",
                "on-tertiary-container": "#424200",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#b1b100",
                "primary-fixed": "#ffdad4",
                "tertiary-fixed": "#eaea00",
                "on-primary": "#ffffff",
                "tertiary-fixed-dim": "#cdcd00",
                "surface-container-lowest": "#ffffff"
            },
            fontFamily: {
                "headline": ["Newsreader"],
                "body": ["Newsreader"],
                "label": ["Newsreader"]
            },
            borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
        },
    },
}
